// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZ7iiizfYuW5qN-bi-ZWbltwLRHDJxFo',
    appId: '1:280199267399:web:657c5f7f9a8da0d53e9d62',
    messagingSenderId: '280199267399',
    projectId: 'note-app-swd62a',
    authDomain: 'note-app-swd62a.firebaseapp.com',
    storageBucket: 'note-app-swd62a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAramCM64Yv1PaWnOaVKu2eoeKPtwsnBa0',
    appId: '1:280199267399:android:916d756c2a8861793e9d62',
    messagingSenderId: '280199267399',
    projectId: 'note-app-swd62a',
    storageBucket: 'note-app-swd62a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwlNtnFlPuW8xDSZrAQEQFFDRz1UvXKA',
    appId: '1:280199267399:ios:00eab61951b3da993e9d62',
    messagingSenderId: '280199267399',
    projectId: 'note-app-swd62a',
    storageBucket: 'note-app-swd62a.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwlNtnFlPuW8xDSZrAQEQFFDRz1UvXKA',
    appId: '1:280199267399:ios:00eab61951b3da993e9d62',
    messagingSenderId: '280199267399',
    projectId: 'note-app-swd62a',
    storageBucket: 'note-app-swd62a.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgZ7iiizfYuW5qN-bi-ZWbltwLRHDJxFo',
    appId: '1:280199267399:web:8fca298de52f671a3e9d62',
    messagingSenderId: '280199267399',
    projectId: 'note-app-swd62a',
    authDomain: 'note-app-swd62a.firebaseapp.com',
    storageBucket: 'note-app-swd62a.firebasestorage.app',
  );

}